README: make installation and test steps clearer
ovn-org/ovn-heater pull request #170
Opened 2023-08-03 09:50 UTC by linup2011

all installation and test steps should be run on ORCHESTRATOR node

2023-08-10 13:31 UTC, dceara requested changes
I left two very minor comments, otherwise looks good to me, thanks!

2023-08-11 00:57 UTC, linup2011 commented on README.md
> +All the following installation steps are run on ORCHESTRATOR
updated

2023-08-11 00:58 UTC, linup2011 commented on README.md
> +Testing steps are executed on ORCHESTRATOR node
updated

2023-08-11 10:35 UTC, dceara approved these changes
LGTM, thanks!

2023-08-11 10:35 UTC, merged